-- MySQL Script generated by MySQL Workbench
-- Wed Oct 11 14:51:04 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_get_colors
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bd_get_colors` ;

-- -----------------------------------------------------
-- Schema bd_get_colors
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_get_colors` DEFAULT CHARACTER SET utf8 ;
USE `bd_get_colors` ;

-- -----------------------------------------------------
-- Table `bd_get_colors`.`tb_historial_password`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_get_colors`.`tb_historial_password` ;

CREATE TABLE IF NOT EXISTS `bd_get_colors`.`tb_historial_password` (
  `historial_password_id` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(150) NOT NULL,
  `responsable_id` INT NOT NULL,
  PRIMARY KEY (`historial_password_id`),
  UNIQUE INDEX `rol_id_UNIQUE` (`historial_password_id` ASC) VISIBLE,
  INDEX `fk_tb_historial_password_tb_responsable1_idx` (`responsable_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_historial_password_tb_responsable1`
    FOREIGN KEY (`responsable_id`)
    REFERENCES `bd_get_colors`.`tb_responsable` (`responsable_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `bd_get_colors`.`tb_recuperar_password`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_get_colors`.`tb_recuperar_password` ;

CREATE TABLE IF NOT EXISTS `bd_get_colors`.`tb_recuperar_password` (
  `recuperar_password_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(40) NOT NULL,
  `token` VARCHAR(150) NOT NULL,
  `expiracion` DATETIME NOT NULL,
  `activo` TINYINT NOT NULL,
  `responsable_id` INT NOT NULL,
  PRIMARY KEY (`recuperar_password_id`),
  UNIQUE INDEX `id_tramite_UNIQUE` (`recuperar_password_id` ASC) VISIBLE,
  INDEX `fk_tb_recuperar_password_tb_responsable1_idx` (`responsable_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_recuperar_password_tb_responsable1`
    FOREIGN KEY (`responsable_id`)
    REFERENCES `bd_get_colors`.`tb_responsable` (`responsable_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `bd_get_colors`.`tb_responsable`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_get_colors`.`tb_responsable` ;

CREATE TABLE IF NOT EXISTS `bd_get_colors`.`tb_responsable` (
  `responsable_id` INT NOT NULL AUTO_INCREMENT,
  `cedula` VARCHAR(20) NOT NULL,
  `email` VARCHAR(40) NOT NULL,
  `nombre` VARCHAR(20) NOT NULL,
  `apellidos` VARCHAR(40) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `password` VARCHAR(150) NOT NULL,
  `fecha` DATETIME NOT NULL,
  `activo` TINYINT NOT NULL,
  `rol_id` INT NOT NULL,
  `seguridad_id` INT NOT NULL,
  PRIMARY KEY (`responsable_id`),
  UNIQUE INDEX `responsable_id_UNIQUE` (`responsable_id` ASC) VISIBLE,
  UNIQUE INDEX `cedula_UNIQUE` (`cedula` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_tb_responsable_tb_rol_idx` (`rol_id` ASC) VISIBLE,
  INDEX `fk_tb_responsable_tb_seguridad1_idx` (`seguridad_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_responsable_tb_rol`
    FOREIGN KEY (`rol_id`)
    REFERENCES `bd_get_colors`.`tb_rol` (`rol_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_responsable_tb_seguridad1`
    FOREIGN KEY (`seguridad_id`)
    REFERENCES `bd_get_colors`.`tb_seguridad` (`seguridad_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `bd_get_colors`.`tb_rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_get_colors`.`tb_rol` ;

CREATE TABLE IF NOT EXISTS `bd_get_colors`.`tb_rol` (
  `rol_id` INT NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(20) NOT NULL,
  `activo` TINYINT NOT NULL,
  PRIMARY KEY (`rol_id`),
  UNIQUE INDEX `rol_id_UNIQUE` (`rol_id` ASC) VISIBLE,
  UNIQUE INDEX `rol_UNIQUE` (`rol` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `bd_get_colors`.`tb_seguridad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_get_colors`.`tb_seguridad` ;

CREATE TABLE IF NOT EXISTS `bd_get_colors`.`tb_seguridad` (
  `seguridad_id` INT NOT NULL AUTO_INCREMENT,
  `expiracion_password` DATETIME NOT NULL,
  `expiracion_bloqueo` DATETIME NOT NULL,
  `numero_intentos` TINYINT NOT NULL,
  PRIMARY KEY (`seguridad_id`),
  UNIQUE INDEX `rol_id_UNIQUE` (`seguridad_id` ASC) VISIBLE);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
